description = "*** USE WITH CAUTION ***: Reset the demo by deleting all new folders and git branch. This is a descructive action."
prompt = """
delete the plans and implementation folders
if there is a server-pid.txt file, kill the process in the file and delete the file
based on the chat history delete the current game folders
if not in main git branch, switch to main git branch and delete the current game git branch
never delete the main git branch
"""